spring:
  application:
    name: search
  profiles:
    active: dev

server:
  port: 8082

# Actuator config
management:
  endpoints:
    web:
      base-path: "/details"
      exposure:
        include: "health,info,metrics"
    jmx:
      exposure:
        include: "health"
  otlp:
    metrics:
      export:
        url: http://localhost:4317
        step: 5
    tracing:
      endpoint: http://localhost:4317}
  tracing:
    otlp:
      endpoint: http://localhost:4317}
  logging:
    otlp:
      endpoint: http://localhost:4317}
  endpoint:
    health:
      probes:
        enabled: true

dgs:
  graphql:
    path: "/graphql"
    introspection:
      enabled: true