services:
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "3001:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    healthcheck:
      test: [ "CMD-SHELL","wget -qO- http://localhost:9090/-/ready | grep -q 'Prometheus Server is Ready'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aviation-network

  mimir:
    image: grafana/mimir:2.17.1
    container_name: mimir
    restart: unless-stopped
    ports:
      - "3002:9009"
    command:
      - "-config.file=/etc/mimir.yaml"
    volumes:
      - mimir_data:/var/mimir
      - ./mimir/config/mimir.yml:/etc/mimir.yaml:ro
    networks:
      - aviation-network

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: [ "CMD-SHELL","wget -qO- http://localhost:3000/api/health | grep -q 'ok'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - aviation-network

volumes:
  prometheus_data:
  mimir_data:
  grafana_data:

networks:
  aviation-network:
    name: aviation-network
    driver: bridge