apiVersion: v1
kind: Service
metadata:
  name: flights-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: flights-service.flights.svc.cluster.local
  ports:
  - port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: aircraft-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: aircraft-service.aircraft.svc.cluster.local
  ports:
  - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: authentication-service.authentication.svc.cluster.local
  ports:
  - port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: search-service.search.svc.cluster.local
  ports:
  - port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: router-service.aviation.svc.cluster.local
  ports:
  - port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: gateway-service.aviation.svc.cluster.local
  ports:
  - port: 4001