apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aviation-ingress
  namespace: aviation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: api.aviation.local
      http:
        paths:
          - path: /flights/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: flights-service
                port:
                  number: 8081
          - path: /flights
            pathType: Prefix
            backend:
              service:
                name: flights-service
                port:
                  number: 8081
          - path: /aircraft/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: aircraft-service
                port:
                  number: 8080
          - path: /aircraft
            pathType: Prefix
            backend:
              service:
                name: aircraft-service
                port:
                  number: 8080