apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aviation-ingress
  namespace: aviation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: api.aviation.local
      http:
        paths:
          - path: /router/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: router-service
                port:
                  number: 4000
          - path: /router
            pathType: Prefix
            backend:
              service:
                name: router-service
                port:
                  number: 4000
          - path: /flights/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: flights-service
                port:
                  number: 8081
          - path: /flights
            pathType: Prefix
            backend:
              service:
                name: flights-service
                port:
                  number: 8081
          - path: /aircraft/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: aircraft-service
                port:
                  number: 8080
          - path: /aircraft
            pathType: Prefix
            backend:
              service:
                name: aircraft-service
                port:
                  number: 8080
          - path: /auth/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-service
                port:
                  number: 8000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: 8000
          - path: /gateway/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-service
                port:
                  number: 4001
          - path: /gateway
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 4001
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-service
                port:
                  number: 4001