apiVersion: v1
kind: Service
metadata:
  name: flights-service
  namespace: aviation
spec:
  type: ExternalName
  externalName: flights-service.flights.svc.cluster.local
  ports:
  - port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: aircraft-service
  namespace: aviation
spec:
  type: ExternalName
  externalName: aircraft-service.aircraft.svc.cluster.local
  ports:
  - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: aviation
spec:
  type: ExternalName
  externalName: search-service.search.svc.cluster.local
  ports:
  - port: 8082