apiVersion: v1
kind: Service
metadata:
  name: aircraft-database
  namespace: aviation
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: aircraft-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aircraft-database
  namespace: aviation
spec:
  serviceName: aircraft-database
  replicas: 1
  selector:
    matchLabels:
      app: aircraft-database
  template:
    metadata:
      labels:
        app: aircraft-database
    spec:
      containers:
        - name: postgres
          image: postgres:17.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: aircraft
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          readinessProbe:
            exec:
              command: [ "pg_isready","-U","postgres","-d","aircraft" ]
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi