apiVersion: v1
kind: Service
metadata:
  name: aircraft-service
  namespace: aviation
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: aircraft-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aircraft-service
  namespace: aviation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aircraft-service
  template:
    metadata:
      labels:
        app: aircraft-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: [ "sh", "-c", "until nc -z aircraft-database.aviation.svc.cluster.local 5432; do sleep 2; done;" ]
        - name: wait-for-cache
          image: busybox
          command: [ "sh", "-c", "until nc -z aircraft-cache.aviation.svc.cluster.local 6379; do sleep 2; done;" ]
      containers:
        - name: aircraft-service
          image: ghcr.io/edinstance/distributed-aviation-system-services/aircraft:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "9090"
            - name: DATABASE_URL
              value: "jdbc:postgresql://aircraft-database:5432/aircraft"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: CACHE_URL
              value: "redis://aircraft-cache:6379"
            - name: LIQUIBASE_ENABLED
              value: "false"
            - name: OTEL_SERVICE_NAME
              value: "aircraft-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://host.docker.internal:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_BSP_SCHEDULE_DELAY
              value: "5000"
          readinessProbe:
            httpGet:
              path: /details/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi