global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "flights-service"
    static_configs:
      - targets: [ "flights-service:8081" ]
    metrics_path: "/metrics"

  - job_name: "aircraft-service"
    static_configs:
      - targets: [ "aircraft-service:8080" ]
    metrics_path: "/details/prometheus"