global:
  scrape_interval: 5s
  evaluation_interval: 5s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "grafana"
    static_configs:
      - targets: [ "grafana:3000" ]

  - job_name: "mimir"
    static_configs:
      - targets: [ "mimir:9009" ]
    metrics_path: "/metrics"

  - job_name: "otel-collector"
    static_configs:
      - targets: [ "otel-collector:9464" ]

  - job_name: "apollo-router"
    static_configs:
      - targets: [ "apollo-router:8089" ]
    metrics_path: "/metrics"

  - job_name: "flights-service"
    static_configs:
      - targets: [ "flights-service:8081" ]
    metrics_path: "/metrics"

