spring:
  application:
    name: aircraft
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/aircraft
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

redis:
  url: redis://localhost:6380

# gRPC server config
grpc:
  server:
    port: 9090

# Actuator config
management:
  endpoints:
    web:
      base-path: "/details"
      exposure:
        include: "health,info,metrics,prometheus"
    jmx:
      exposure:
        include: "health"
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    metrics:
      export:
        url: http://localhost:4317
  endpoint:
    health:
      probes:
        enabled: true

dgs:
  graphql:
    path: "/graphql"
    introspection:
      enabled: true