spring:
  application:
    name: aircraft
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/aircraft
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml
    enabled: false

redis:
  url: redis://localhost:6380

# Actuator config
management:
  endpoints:
    web:
      base-path: "/details"
    jmx:
      exposure:
        include: "health"

dgs:
  graphql:
    path: "/graphql"
    introspection:
      enabled: true