apiVersion: v1
kind: Service
metadata:
  name: flights-cache
  namespace: aviation
spec:
  ports:
    - port: 6379
  selector:
    app: flights-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-cache
  namespace: aviation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-cache
  template:
    metadata:
      labels:
        app: flights-cache
    spec:
      containers:
        - name: redis
          image: redis:8.2
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: [ "redis-cli","ping" ]
            initialDelaySeconds: 5
            periodSeconds: 5