apiVersion: v1
kind: Service
metadata:
  name: flights-service
  namespace: flights
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: flights-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-service
  namespace: flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-service
  template:
    metadata:
      labels:
        app: flights-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: [ "sh", "-c", "until nc -z flights-database.flights.svc.cluster.local 5432; do sleep 2; done;" ]
        - name: wait-for-cache
          image: busybox
          command: [ "sh", "-c", "until nc -z flights-cache.flights.svc.cluster.local 6379; do sleep 2; done;" ]
      containers:
        - name: flights-service
          image: ghcr.io/edinstance/distributed-aviation-system-services/flights:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@flights-database:5432/flights?sslmode=disable"
            - name: CACHE_URL
              value: "redis://flights-cache:6379"
            - name: ENVIRONMENT
              value: "prod"
            - name: PORT
              value: "8081"
            - name: AIRCRAFT_SERVICE_GRPC_URL
              value: aircraft-service.aircraft:9090
            - name: OTLP_GRPC_URL
              value: otel-collector.monitoring:4317
            - name: KAFKA_BROKER_URL
              value: kafka.messaging.svc.cluster.local:9092
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: http://schema-registry.messaging.svc.cluster.local:8081
            - name: KAFKA_FLIGHTS_TOPIC
              value: flights
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi