apiVersion: batch/v1
kind: Job
metadata:
  name: authentication-migrations
  namespace: aviation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to become available..."
              until nc -z authentication-database.aviation.svc.cluster.local 5432; do
                echo "Still waiting for DB..."; sleep 2;
              done
              echo "Database is ready!"
        - name: wait-for-keys
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for keys to be generated..."
              until [ -f /keys/private.pem ] && [ -f /keys/public.pem ]; do
                echo "Still waiting for keys..."; sleep 2;
              done
              echo "Keys are ready!"
          volumeMounts:
            - name: keys-volume
              mountPath: /keys
      containers:
        - name: authentication-service
          image: ghcr.io/edinstance/distributed-aviation-system-services/authentication-migrate:dev
          env:
            - name: SECRET_KEY
              value: insecure-key
            - name: KEYS_DIR
              value: /keys
            - name: KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-key-password
                  key: password
            - name: DATABASE_NAME
              value: authentication
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-database-password
                  key: password
            - name: DATABASE_HOST
              value: authentication-database
            - name: DATABASE_PORT
              value: "5432"
          volumeMounts:
            - name: keys-volume
              mountPath: /keys
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: keys-volume
          persistentVolumeClaim:
            claimName: authentication-keys-pvc