apiVersion: v1
kind: Secret
metadata:
  name: authentication-key-password
  namespace: authentication
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-database-password
  namespace: authentication
type: Opaque
data:
  password: cG9zdGdyZXM=
---